
[pass_b4b]
size = [3, 5]
variables = [
    "SW_flux_up_at_model_top",
    "LW_flux_up_at_model_top",
    "SW_flux_dn_at_model_top",
    "LiqWaterPath",
]
ntimes = 12
ninst = 30
hist_file_fmt = "scream_{inst:04d}.h.{time}"
ensembles = ["baseline", "test"]
[pass_b4b.baseline]
ensemble = { seed = true }
name = "mvkxx_pass_b4b_base"
[pass_b4b.test]
ensemble = { seed = true }
name = "mvkxx_pass_b4b_test"

[pass_nb4b]
size = [3, 5]
variables = [
    "SW_flux_up_at_model_top",
    "LW_flux_up_at_model_top",
    "SW_flux_dn_at_model_top",
    "LiqWaterPath",
]
ntimes = 12
ninst = 30
hist_file_fmt = "scream_{inst:04d}.h.{time}"
ensembles = ["baseline", "test"]
[pass_nb4b.baseline]
ensemble = { seed = false }
name = "mvkxx_pass_nb4b_base"
[pass_nb4b.test]
ensemble = { seed = false }
name = "mvkxx_pass_nb4b_test"

[fail]
size = [3, 5]
variables = [
    "SW_flux_up_at_model_top",
    "LW_flux_up_at_model_top",
    "SW_flux_dn_at_model_top",
    "LiqWaterPath",
]
ntimes = 12
ninst = 30
hist_file_fmt = "scream_{inst:04d}.h.{time}"
ensembles = ["baseline", "test"]
[fail.baseline]
ensemble = { seed = false, popmean = 1.0 }
name = "mvkxx_fail_base"
[fail.test]
ensemble = { seed = false, popmean = 2.0 }
name = "mvkxx_fail_test"
